# Start-up script executed if a login shell.

# set default permission of file to 644 (rw-r--r--)
umask 022

# At this point, /etc/zprofile has been executed (after ~/.zshenv)
# which messes up $PATH due to the execution of `path_helper`.
# Correct $PATH so that /usr/local/bin, etc. would come after
# custom, local-preferred paths.
path=( ${path[@]:#/usr/local/bin} )
path=( ${path[@]:#/usr/local/sbin} )
path=( ${path[@]:#/usr/bin} )
path=( ${path[@]:#/usr/sbin} )
path=( ${path[@]:#/sbin} )
path=(
  $path
  "/usr/local/bin"
  "/usr/local/sbin"
  "/usr/bin"
  "/usr/sbin"
  "/sbin"
)

# Let ~/.local/bin take precedence
if ! (( ${path[(I)$HOME/.local/bin]} )); then
  path=( $HOME/.local/bin $path )
fi
eval "$(/opt/homebrew/bin/brew shellenv)"


autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/bit bit

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
export PTPYTHON_CONFIG_HOME="/Users/sungminoh/.config/ptpython"
